#!/usr/bin/env python

# from lib.uwfoods import get_taco_restaurants
from lib.taco_lover import notify_taco_lover, get_taco_lovers
from lib.config import Config

if __name__ == '__main__':
    taco_lovers = get_taco_lovers()
    for taco_lover in taco_lovers:
        notify_taco_lover(taco_lover, "Yay! Tacos! Head over to V1 to get Tacos")
        print "Notified %s" % taco_lover
    # notify_taco_lover("2266064222", "Yay! Tacos! Head over to V1 to get Tacos")
    # restaurants = get_taco_restaurants()

    # if len(restaurants) > 0:




