#!/usr/bin/env python

from datetime import datetime

from lib.uwfoods import get_taco_restaurants
from lib.taco_lover import notify_taco_lover
from lib.config import Config

if __name__ == '__main__':
     tacos = get_taco_restaurants(datetime.today().date())

     if len(tacos) > 0:
		 taco_lovers = get_taco_lovers()
		 msg = []
		 for taco in tacos:
			 msg.append(' ' + taco['restaurant'] + ' is serving ' + taco['food'] + ' for ' + taco['meal'])

		 for taco_lover in taco_lovers:
			 notify_taco_lover(taco_lover, 'Yay! Tacos!' + ','.join(msg)

